config/routes.rb
Rails.application.routes.draw do
  resources :payment_ways
  resources :memberships
  resources :detail_purchase_receipts
  resources :purchase_receipts
  resources :details
  resources :providers
  resources :outflows
  resources :discounts
  resources :societies
  resources :receipts
  resources :clients
  resources :categories
  resources :products
  devise_for :users, :controllers => { :registrations => "user/registrations" }
    root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :discounts
  has_many :societies, through: :discounts
  has_many :products
  belongs_to :user
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :receipts
  belongs_to :membership
  belongs_to :user
  accepts_nested_attributes_for :receipts
  

  #after_create :save_receipt
  #after_create :send_mail

  def f_pago=(f_pago)
    @f_pago = f_pago
  end
  def societyId=(id)
    @society_id=id
  end
  def valor=(value)
    @valor = value
  end
  def soporte=(support)
    @support = support
  end
  def sed_mail
    @s = Society.find(params[:self.society_id])
    SocietyMailer.new_society(@s).deliver_later
  end
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :receipt
  belongs_to :product
  belongs_to :user
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :society
  belongs_to :category
  belongs_to :user
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :society
  has_many :clients
  belongs_to :user
  has_many :receipts

  accepts_nested_attributes_for :clients
  accepts_nested_attributes_for :receipts

  after_create :save_client
  after_create :fechas
  after_create :save_receipt

  def t_cedula=(cedula)
    @t_c = cedula
  end
  def n_cedula=(numero)
    @numeroC = numero
  end
  def nombreA=(nom)
    @nombreA=nom
  end
  def apellido=(ap)
    @apellido=ap
  end
  def telefono=(tel)
    @telefono=tel
  end
  def direccion=(direc)
    @direccion=direc
  end
  def pais=(pais)
    @pais=pais
  end
  def ciudad=(c)
    @ciudad=c
  end
  def email=(email)
    @email=email
  end
  def formaDePago=(fp)
    @f_pago = fp
  end
  def valor=(value)
    @valor = value
  end
  def soporte=(s)
    @support = s
  end

def save_client
  Client.create( documento: @numeroC, tipo_documento: @t_c, nombre: @nombreA, apellido: @apellido, telefono: @telefono, direccion: @direccion, pais: @pais, ciudad: @ciudad, email: @email, membership_id: self.id)

end
  def save_receipt
    Receipt.create(fecha: self.fecha_afiliacion, client_id: Client.last.id, forma_de_pago_id: @f_pago, membership_id: self.id, valor_total: @valor, soporte: @support)

  end
  def s_receipt(fecha, cliente_id, formaPago, membership_id, valor, soporte )
    Receipt.create(fecha: fecha, client_id: cliente_id, forma_de_pago_id: formaPago, membership_id: membership_id, valor_total: valor, soporte: soporte)

  end
  def updateAcomulado(valor)
    #modificar el volor acomulado por cada cuota

    valorF = self.pago_acomulado+valor
    self.update(pago_acomulado: valorF)

    #cambio de fecha poxima cuota
    fecha = self.fecha_cuota
    if self.periodicidad == 'Anual'

      #self.update(fecha_vencimiento: t+(60*60*24*365))
      #self.update(fecha_cuota: t+(60*60*24*365))
    elsif self.periodicidad == 'Mensual'
      puts (self.fecha_cuota + 2592000)
      #self.update(fecha_vencimiento: fecha+2592000)
      #self.update(fecha_cuota: fecha+2592000 )
    elsif self.periodicidad == 'Semestral'
      #self.update(fecha_cuota: fecha+15768000)
      #self.update(fecha_vencimiento: fecha+15768000)

    end

  end
  def fechas
    t = Time.new
    self.update(fecha_afiliacion: t)
    if self.periodicidad == 'Anual'
      self.update(fecha_vencimiento: t+(60*60*24*365))
      self.update(fecha_cuota: t+(60*60*24*365))
    elsif self.periodicidad == 'Mensual'
      self.update(fecha_vencimiento: t+2592000)
      self.update(fecha_cuota: t+2592000 )
    elsif self.periodicidad == 'Semestral'
      self.update(fecha_cuota: t+15768000)
      self.update(fecha_vencimiento: t+15768000)

    end
      self.update(estado: TRUE)
  end
end

app/models/outflow.rb
class Outflow < ApplicationRecord
    belongs_to :user
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/payment_way.rb
class PaymentWay < ApplicationRecord
    
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :detail_purchase_receipts
  has_many :details
  belongs_to :user
end

app/models/provider.rb
class Provider < ApplicationRecord
    has_many :purchase_receipts
    belongs_to :user
end

app/models/purchase_receipt.rb
class PurchaseReceipt < ApplicationRecord
  has_many :detail_purchase_receipts
  belongs_to :provider
  accepts_nested_attributes_for :detail_purchase_receipts,reject_if: :all_blank,allow_destroy: true
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :client
  belongs_to :forma_de_pago
  belongs_to :membership
  belongs_to :user
  has_many :details
  #has_many :details
 # has_attached_file :soporte, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #validates_attachment_content_type :soporte, content_type: /\Aimage\/.*\z/

end

app/models/society.rb
class Society < ApplicationRecord
  has_many :discounts
  has_many :categories, through: :discounts
  has_many :memberships
  belongs_to :user

  accepts_nested_attributes_for :discounts,reject_if: :all_blank,allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  def full_name
  return "#{first_name} #{last_name}".strip if (first_name || last_name)
  "Anonymous"
  end
  
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:fecha_afiliacion, :periodicidad, :fecha_vencimiento, :fecha_cuota)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/outflows_helper.rb
module OutflowsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(membership) do |f| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha_afiliacion %>
    <%= f.date_select :fecha_afiliacion %>
  </div>

  <div class="field">
    <%= f.label :periodicidad %>
    <%= f.text_field :periodicidad %>
  </div>

  <div class="field">
    <%= f.label :fecha_vencimiento %>
    <%= f.date_select :fecha_vencimiento %>
  </div>

  <div class="field">
    <%= f.label :fecha_cuota %>
    <%= f.date_select :fecha_cuota %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Fecha afiliacion</th>
      <th>Periodicidad</th>
      <th>Fecha vencimiento</th>
      <th>Fecha cuota</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.fecha_afiliacion %></td>
        <td><%= membership.periodicidad %></td>
        <td><%= membership.fecha_vencimiento %></td>
        <td><%= membership.fecha_cuota %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha afiliacion:</strong>
  <%= @membership.fecha_afiliacion %>
</p>

<p>
  <strong>Periodicidad:</strong>
  <%= @membership.periodicidad %>
</p>

<p>
  <strong>Fecha vencimiento:</strong>
  <%= @membership.fecha_vencimiento %>
</p>

<p>
  <strong>Fecha cuota:</strong>
  <%= @membership.fecha_cuota %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>