config/routes.rb
Rails.application.routes.draw do
  resources :payment_ways
  resources :memberships
  resources :detail_purchase_receipts
  resources :purchase_receipts
  resources :details
  resources :providers
  resources :outflows
  resources :discounts
  resources :societies
  resources :receipts
  resources :clients
  resources :categories
  resources :products
  devise_for :users, :controllers => { :registrations => "user/registrations" }
    root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/detail_purchase_receipt.rb
class DetailPurchaseReceipt < ApplicationRecord
  belongs_to :purchase_receipt
  belongs_to :product
end

app/controllers/detail_purchase_receipts_controller.rb
class DetailPurchaseReceiptsController < ApplicationController
  before_action :set_detail_purchase_receipt, only: [:show, :edit, :update, :destroy]

  # GET /detail_purchase_receipts
  # GET /detail_purchase_receipts.json
  def index
    @detail_purchase_receipts = DetailPurchaseReceipt.all
  end

  # GET /detail_purchase_receipts/1
  # GET /detail_purchase_receipts/1.json
  def show
  end

  # GET /detail_purchase_receipts/new
  def new
    @detail_purchase_receipt = DetailPurchaseReceipt.new
  end

  # GET /detail_purchase_receipts/1/edit
  def edit
  end

  # POST /detail_purchase_receipts
  # POST /detail_purchase_receipts.json
  def create
    @detail_purchase_receipt = DetailPurchaseReceipt.new(detail_purchase_receipt_params)

    respond_to do |format|
      if @detail_purchase_receipt.save
        format.html { redirect_to @detail_purchase_receipt, notice: 'Detail purchase receipt was successfully created.' }
        format.json { render :show, status: :created, location: @detail_purchase_receipt }
      else
        format.html { render :new }
        format.json { render json: @detail_purchase_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detail_purchase_receipts/1
  # PATCH/PUT /detail_purchase_receipts/1.json
  def update
    respond_to do |format|
      if @detail_purchase_receipt.update(detail_purchase_receipt_params)
        format.html { redirect_to @detail_purchase_receipt, notice: 'Detail purchase receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail_purchase_receipt }
      else
        format.html { render :edit }
        format.json { render json: @detail_purchase_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detail_purchase_receipts/1
  # DELETE /detail_purchase_receipts/1.json
  def destroy
    @detail_purchase_receipt.destroy
    respond_to do |format|
      format.html { redirect_to detail_purchase_receipts_url, notice: 'Detail purchase receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail_purchase_receipt
      @detail_purchase_receipt = DetailPurchaseReceipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_purchase_receipt_params
      params.require(:detail_purchase_receipt).permit(:cantidad, :valor_total)
    end
end

app/helpers/detail_purchase_receipts_helper.rb
module DetailPurchaseReceiptsHelper
end

app/views/detail_purchase_receipts/_form.html.erb
<%= form_for(detail_purchase_receipt) do |f| %>
  <% if detail_purchase_receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detail_purchase_receipt.errors.count, "error") %> prohibited this detail_purchase_receipt from being saved:</h2>

      <ul>
      <% detail_purchase_receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cantidad %>
    <%= f.number_field :cantidad %>
  </div>

  <div class="field">
    <%= f.label :valor_total %>
    <%= f.text_field :valor_total %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/detail_purchase_receipts/edit.html.erb
<h1>Editing Detail Purchase Receipt</h1>

<%= render 'form', detail_purchase_receipt: @detail_purchase_receipt %>

<%= link_to 'Show', @detail_purchase_receipt %> |
<%= link_to 'Back', detail_purchase_receipts_path %>

app/views/detail_purchase_receipts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Detail Purchase Receipts</h1>

<table>
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Valor total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @detail_purchase_receipts.each do |detail_purchase_receipt| %>
      <tr>
        <td><%= detail_purchase_receipt.cantidad %></td>
        <td><%= detail_purchase_receipt.valor_total %></td>
        <td><%= link_to 'Show', detail_purchase_receipt %></td>
        <td><%= link_to 'Edit', edit_detail_purchase_receipt_path(detail_purchase_receipt) %></td>
        <td><%= link_to 'Destroy', detail_purchase_receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail Purchase Receipt', new_detail_purchase_receipt_path %>

app/views/detail_purchase_receipts/new.html.erb
<h1>New Detail Purchase Receipt</h1>

<%= render 'form', detail_purchase_receipt: @detail_purchase_receipt %>

<%= link_to 'Back', detail_purchase_receipts_path %>

app/views/detail_purchase_receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cantidad:</strong>
  <%= @detail_purchase_receipt.cantidad %>
</p>

<p>
  <strong>Valor total:</strong>
  <%= @detail_purchase_receipt.valor_total %>
</p>

<%= link_to 'Edit', edit_detail_purchase_receipt_path(@detail_purchase_receipt) %> |
<%= link_to 'Back', detail_purchase_receipts_path %>